### ISSUE TITLE
Todo Database Create/Update/Delete

### ISSUE THREAD

**Issue by LeeChoongHwan** [AndroidEarlyBirdy/EarlyBirdy#76]
- [ ] 데이터 베이스에 Todo 추가
- [ ] 데이터 베이스 Todo 수정
- [ ] 데이터 베이스 Todo 삭제
